### ISSUE TITLE
Missing attribution statement/link to N8VEM/Zeta SBC

### ISSUE THREAD

**Issue by skiselev** [electrified/rc2014-ds1302-rtc#1]
The RTC implementation appears to be largely based on N8VEM/RetroBrew Computers and Zeta SBC.
Please add an attribution statement, for example "The design is based on RetroBrew Computers SBC and Zeta SBC"
And the links to these projects:
RetroBrew Computers SBC V2: https://retrobrewcomputers.org/doku.php?id=boards:sbc:sbc_v2:start
Zeta SBC V2: http://www.malinov.com/Home/sergeys-projects/zeta-sbc-v2

**Comment by electrified** [comment]
Hi Sergey,

You are correct it was largely based on the Zeta 2 circuit. Apologies for not crediting your project, this was an oversight. I've added a statement to the first paragraph of the readme.

The IDE board which was also retrobrew inspired already has a similar statement: https://github.com/electrified/rc2014-82c55-ide

Many thanks for your work on these projects!

**Comment by skiselev** [comment]
Thank you!
